version: '3.1'

services:
  joomla:
    image: joomla:4.2.7-php8.1-apache
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "4242:80"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: "demo-ppZ5hnvK2ZEpR9yhRKA7"

  joomladb:
    image: mysql:8.0.32-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "demo-ppZ5hnvK2ZEpR9yhRKA7"